version: '3.8'

services:
  # NestJS Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-app-backend
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health" ]
      interval: 20s
      timeout: 10s
      retries: 3
      start_period: 30s

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-app-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3001:5173" # Vite dev server runs on 5173 by default
    networks:
      - app-network
    volumes:
      - ./frontend:/app  # Mount source code for hot reloading
      - /app/node_modules # Preserve container node_modules
    environment:
      - VITE_API_URL=http://backend:3000/tasks # Use container name for service-to-service communication
      - CHOKIDAR_USEPOLLING=true # Enable polling for file changes in Docker

networks:
  app-network:
    driver: bridge